language: java
jdk: oraclejdk8
branches:
  only: master
install: true
script: ".travis/build.sh"
after_success: ".travis/notify.sh Travis-Success"
after_failure: ".travis/notify.sh Travis-Failure"
env:
  global:
  - secure: cht+NZd4MZoX5VOKGo6GJqO8vpGCN8UzMOsElWFawjOr5qV4VnqcpHFskoaebTvz3Qa8j4V6J+2ovUwJsdJotThBEZRm5tizj9ZelmqAVJ3vzOsPjlmIcZK130u85KaUe+6+2DKLLn7VurA6iWcOWz0Lwo6wW+rQhUbNwojL5cI=
  - secure: Oo756mCBgxDYQMXr9aA3Vo8+Zv3Y/vgEOwRB8PBjtKOOec/+NH+cZHs0octVxbi3cgl5tiNe6w1fZCOLt72UY2DsZeYn9vsasckNlaJWRLDwqysdIJF1MkdU3KlLzb5CRJ8OoHhrqCsmQCN0cP0JFXrUqOPRIcj1E0PZ1srQqag=
